import React from "react";

function Workshop6() {
    return( 
        <>
<p>A widespread assumption in the linguistic literature is that language change is an expected, and even unavoidable, result of language contact. The association between contact and change is based on the assumption that bilingualism sets the stage for a variety of linguistic phenomena that result in change of one kind or another: code-switching, borrowing, addition or loss of grammatical and lexical categories, development of periphrastic constructions, and overgeneralization of forms following a regularizing pattern, among other kinds of interference. This scenario often results in the development of innovative language uses and/or the acceleration of changes that are underway in a contact variety as compared to monolingual varieties of the same language. Much less attention, however, has been devoted to the opposite scenario, that is, when language contact promotes the retention of an older trait in a given language, and even the reversal or inhibition of a change that is taking place in non-contact varieties of the language in question.</p>
 
 <p>The mechanism to explain contact induced non-change is fairly straightforward. Processes of language change are often characterized by the emergence of a new form or construction that becomes interchangeable in at least one linguistic environment with a pre-existing one. Once this new form increases its frequency to the point of replacing entirely the older one, the change is complete. However, in a language-contact situation use of the traditional variant may be reinforced by (a) the existence of a parallel structure in the contact language and/or (b) the absence of a structural equivalent for the innovative variant in the contact language. In such cases change could be delayed, and thus the spread of the innovative variant would progress more slowly than in non-contact varieties of the same language. </p>
 <p> Variationist sociolinguistics and experimental studies on bilingualism and second language acquisition have investigated contact-induced changes through the synchronic observation of different generational groups. Even if we accept the empirical value of these approaches, there is no question that, in establishing contact-induced change, we need to look at the history of the languages involved and examine whether the proposed interference features were not present in the pre-contact variety, that is, there needs to be proof that the receiving language has changed by innovating these features. The inclusion of a historical perspective thus enriches the study of language contact: only in this way can we verify that phenomena identified as deviations from the monolingual norm did not already exist during pre-contact situations. And so, it is always valuable to complement studies on apparent language change with the direct observation of older stages of languages in order to trace out the history of interference phenomena across time.</p>
  
<p> The objective of this workshop is to explore the possibilities provided by historical research to the study of alternate outcomes of language contact, and more specifically contact-induced non-change. As such we welcome historical investigations that illustrate with specific case studies the role of language contact in the retention of older variables. We are also interested in the discussion of methodological problems with establishing the existence of contact-induced retention in particular instances.</p>        </>
        )
    }
    
    export default Workshop6;