export const data = [
    {id: 90, type: 'talk', day: 'monday', time: '1130', room: 'L1', author: ['Laura Arnold'], title: 'The multiple causes of Split Inalienable Coding in northwest New Guinea: Contact meets drift', workshop:'' },
    {id: 200, type: 'talk', day: 'monday', time: '1130', room: 'L2', author: ['Jack Hoeksema'], title: 'Approximative adverbs in modern and premodern languages', workshop:'', link:''},
    {id: 205, type: 'talk', day: 'monday', time: '1130', room: 'L3', author: ['Patrick Honeybone'], title: 'Should fortition have a place in diachronic phonological typology?', workshop:''},
    {id: 270, type: 'talk', day: 'monday', time: '1130', room: 'L6', author: ['Michela Cennamo'], title: 'Paths of change in the diachrony of anti causatives in Romance: the rise and fall of lability', workshop:''},
    {id: 229, type: 'talk', day: 'monday', time: '1130', room: 'C1', author: ['Stefan Hartmann', 'Lena Schnee'], title: 'Disentangling the constructional semantics of German future constructions', workshop:''},
    {id: 11, type: 'talk', day: 'monday', time: '1130', room: 'C4', author: ['Ilja Seržant'], title: 'Cyclic changes in verbal person-number indexes are unlikely', workshop:''},
    {id: 106, type: 'talk', day: 'monday', time: '1130', room: 'C6', author: ['Lena Kaltenbach','Carola Trips'], title: 'Language contact through translation as priming in historical data', workshop:''},
    {id: 134, type: 'talk', day: 'monday', time: '1200', room: 'L1', author:['Chris Lasse Däbritz'], title: 'Grammatical substitution and attrition in Taimyr Evenki – Structural patterns of indigenous language contact in Northern Siberia at the beginning of the 20th century', workshop: '' },
    {id: 64, type: 'talk', day: 'monday', time: '1200', room: 'L2', author:['Nicola Swinburne'], title: 'Evidence for the structure of late Middle - early Modern English do-support using comparisons with present day Camuno', workshop: '' },
    {id: 256, type: 'talk', day: 'monday', time: '1200', room :'L3', author:['Shelece Easterday'], title: 'Reconciling diachronic and synchronic accounts of ejectivization', workshop: '' },
    {id: 139, type: 'talk', day: 'monday', time: '1200', room: 'L6', author: ['Mihaela Ilioaia'], title:'Toward canonical marking of core arguments in Romanian? The case of plăcea', workshop: ''},
    {id: 204, type: 'talk', day: 'monday', time: '1200', room: 'C1', author: ['Tanja Ackermann'], title: 'The evolution of a pragmatic marker in German: The formal and functional development of bitte ‘please’', workshop: ''},
    {id: 143, type: 'talk', day: 'monday', time: '1200', room: 'C4', author: ['Simon Aerts'], title:'Alea iacta est:  A "language ecology" approach to the diachrony of the Latin passive', workshop: ''},
    {id: 217, type: 'talk', day: 'monday', time: '1200', room: 'C6', author: ['Evie Coussé'], title:'Using translated texts in historical linguistics: Turning Challenges into opportunities', workshop: ''},
    {id: 341, type: 'talk', day: 'monday', time: '1230', room: 'L1', author: ['Andrés Enrique-Arias'], title:'The Uniformitarian Principle and contact-induced change: The case of Spanish in Mallorca', workshop: ''},
    {id: 181, type: 'talk', day: 'monday', time: '1230', room: 'L2', author: ['Anna Cichosz'], title:'V-final conjunct clauses in Old English: function and syntactic status', workshop: ''},
    {id: 173, type: 'talk', day: 'monday', time: '1230', room: 'L3', author: ['Tihomir Rangelov'], title:'Exploring unusual sound change: The prenasalised and plain bilabial trills in the languages of Malekula Island (Vanuatu)', workshop: ''},
    {id: 50, type: 'talk', day: 'monday', time: '1230', room: 'L6', author: ['Xavier Bach'], title:'Negation in Gallo-Romance dialects: contact with differential development', workshop: ''},
    {id: 113, type: 'talk', day: 'monday', time: '1230', room: 'C1', author: ['Lourens Visser'], title: 'The Adverbs of Degree in Old and Middle West Germanic Languages', workshop: ''},
    {id: 325, type: 'talk', day: 'monday', time: '1230', room: 'C4', author: ['Muriel Norde'], title:'Hapaxes in word formation: heralds or happenstance?', workshop: ''},
    {id: 111, type: 'talk', day: 'monday', time: '1230', room: 'C6', author: ['Machteld de Vos'], title:'Norm versus usage in strong verbs in 17th century Dutch newspaper language', workshop: ''},
    {id: 379, type: 'talk', day: 'monday', time: '1345', room: 'L1', author: ['Jóhanna Barðdal'], title:'How to Reconstruct Case and Argument Structure for Inconsistent Correspondence Sets Across Daughter Languages: The Case of ‘Suffice’ in Germanic', workshop: ''},
    {id: 294, type: 'talk', day: 'monday', time: '1345', room: 'L2', author: ['Marieke Meelen', 'Ian Roberts'], title:'Extending Parametric Comparison: A Preliminary Investigation of Celtic', workshop: ''},
    {id: 292, type: 'talk', day: 'monday', time: '1345', room: 'L3', author: ['Ranjan Sen'], title:'Cycle Psychology: Experimentally Testing the Life Cycle of Phonological Change', workshop: ''},
    {id: 86, type: 'talk', day: 'monday', time: '1345', room: 'L6', author: ['Barthe Bloom'], title:'Left peripheral so in Early New High German narratives', workshop: ''},    
    {id: 233, type: 'talk', day: 'monday', time: '1345', room: 'C1', author: ['Ezra la Roi'], title:'Life-cycles of counterfactual mood across a millennium of Ancient Greek (VIIIBC-IIIAD)', workshop: ''},
    {id: 366, type: 'talk', day: 'monday', time: '1345', room: 'C4', author: ['Stefano Canalis'], title:'Pretonic mid vowel raising in Old Tuscan', workshop: ''},
    {id: 212, type: 'talk', day: 'monday', time: '1345', room: 'C6', author: ['Don Daniels'], title:'Irregular sound change in the Minjim languages', workshop: ''},
    {id: 109, type: 'talk', day: 'monday', time: '1415', room: 'L1', author: ['Lea Schäfer', 'Edgar Baumgärtner', 'Marc Brode'], title:'Structure of a middle voice in Germanic high contact varieties ', workshop: ''},
    {id: 279, type: 'talk', day: 'monday', time: '1415', room: 'L2', author: ['Krishnan Ram-Prasad'], title:'Past and Non-Past: Parametric diachrony in the tense and aspect systems of ancient Indo-European languages', workshop: ''},
    {id: 340, type: 'talk', day: 'monday', time: '1415', room: 'L3', author: ['Pavel Iosad'], title:'The life cycle of phonological patterns explains drift in sound change', workshop: ''},
    {id: 183, type: 'talk', day: 'monday', time: '1415', room: 'L6', author: ['Nigel Vincent', 'Max W. Wheeler'], title:'Romance GO + infinitive: past and future, home and away', workshop: ''},
    {id: 98, type: 'talk', day: 'monday', time: '1415', room: 'C1', author: ['Theodore Markopoulos', 'Aglaia Trigka'], title:'Piga na peso : De-allative avertive construction(s) in the history of Greek', workshop: ''},
    {id: 132, type: 'talk', day: 'monday', time: '1415', room: 'C4', author: ['Jakob Halfmann'], title:'The diachronic typology of retroflex vowels ', workshop: ''},
    {id: 175, type: 'talk', day: 'monday', time: '1415', room: 'C6', author: ['Danny Law','Justin Power', 'David Quinto-Pozos'], title:'Obstacles to regular change in signed languages', workshop: ''},
    {id: 220, type: 'talk', day: 'monday', time: '1445', room: 'L1', author: ['Isabell Jänich'], title:'The Emergence of a Hybrid Pro-form System in the History of German', workshop: ''},
    {id: 298, type: 'talk', day: 'monday', time: '1445', room: 'L2', author: ['Ian Roberts', 'James Baker', 'Marieke Meelen', 'Krishnan Ram-Prasad'], title:'Extending Parametric Comparison: Some Preliminary Results on Older Indo-European Languages', workshop: ''},
    {id: 250, type: 'talk', day: 'monday', time: '1445', room: 'L3', author: ['Roslyn Burns'], title:'Deriving Listener-Driven Sound Change in a Harmonic Grammar', workshop: ''},
    {id: 115, type: 'talk', day: 'monday', time: '1445', room: 'L6', author: ['Ulla Stroh-Wollin'], title:'The development of definite articles - a process along two paths', workshop: ''},
    {id: 108, type: 'talk', day: 'monday', time: '1445', room: 'C1', author: ['Domenica Romagno'], title:'The curious case of the transitive middle in ancient Indo-European languages', workshop: ''},
    {id: 35, type: 'talk', day: 'monday', time: '1445', room: 'C4', author: ['Andre Zampaulo'], title:'Low surprisal and the emergence of /ɐ̃w̃/ in the history of Portuguese', workshop: ''},
    {id: 258, type: 'talk', day: 'monday', time: '1445', room: 'C6', author: ['Rikker Dockum'], title:'The dialexical set: a diagnostic tool for studying sound change', workshop: ''},
    {id: 26, type: 'poster', day: 'monday', time: '1515', room: '', author: ['Giacomo Iazzetta'], title:'Understanding the role of language policy in the construction and maintenance of inequalities in MOrocco and Tunisia after the Arab Spring', workshop: ''},
    {id: 32, type: 'poster', day: 'monday', time: '1515', room: '', author: ['Yesha Mahadeo-Doorgakant'], title:'The evolution of Kreol Morisien (KM) in the Mauritian', workshop: ''},
    {id: 48, type: 'poster', day: 'monday', time: '1515', room: '', author: ['Nathalie Fromm'], title:'Diachronic development of the former feminine ō-stems in German dialects', workshop: ''},
    {id: 133, type: 'poster', day: 'monday', time: '1515', room: '', author: ['Penying Wang'], title:'Contact-induced change in sememe structure—A case study of the taste term salty in Chinese dialects', workshop: ''},
    {id: 140, type: 'poster', day: 'monday', time: '1515', room: '', author: ['Lucia Assenzi'], title:'The evolution of reported speech in German newspapers of the 18th and 19th century: Evidential strategies, epistemic modality and the expression of reliability', workshop: ''},
    {id: 153, type: 'poster', day: 'monday', time: '1515', room: '', author: ['Nino Amiridze', 'Zurab Baratashvili', 'Giorgi Jgharkava', 'Medea Sagliani'], title: 'Identifying the immediate donor in the presence of several: Preverbs in loan verb accommodation in Megrelian and Svan', workshop: ''},
    {id: 155, type: 'poster', day: 'monday', time: '1515', room: '', author: ['Bipasha Patgiri'], title:'Prosodic Structure of Nalbaria Assamese', workshop: ''},
    {id: 162, type: 'poster', day: 'monday', time: '1515', room: '', author: ['Adrienne Dömötör'], title:'From quotative to causation – the history of Hungarian mondván "saying"', workshop: ''},
    {id: 191, type: 'poster', day: 'monday', time: '1515', room: '', author: ['Laila Alhazmi'], title:'Status and Dynamism of an Endangered Language in Saudi Arabia: Towards a Revitalization Project', workshop: ''},
    {id: 67, type: 'poster', day: 'monday', time: '1515', room: '', author: ['Csilla Ilona Dér'], title:'Independence with or without ellipsis? About the evolution of hogy "that" insubordinate clauses in Hungarian', workshop: ''},
    {id: 73, type: 'poster', day: 'monday', time: '1515', room: '', author: ['Camiel Hamans'], title:'Recognition as a factor in language change', workshop: ''},
    {id: 96, type: 'poster', day: 'monday', time: '1515', room: '', author: ['Noemi De Pasquale', 'Anetta Kopecka'], title: 'Linguistic conceptualizations of auditory perception: a text-based study of Latin', workshop: ''},
    {id: 102, type: 'poster', day: 'monday', time: '1515', room: '', author: ['Harry Lönnroth', 'Theresia Pettersson'], title: 'From spoken utterance to written transcript: The textual process of court records in Early Modern Sweden', workshop: ''},
    {id: 116, type: 'poster', day: 'monday', time: '1515', room: '', author: ['Savithry Namboodiripad'], title:'Using experimental methods to create a typology of contact-induced change in constituent order', workshop: ''},
    {id: 223, type: 'poster', day: 'monday', time: '1515', room: '', author: ['Aleksandrs Berdicevskis', 'Evie Coussé', 'Yvonne Adesam'], title:'Any seeds can be sown, but which ones will sprout? Exploring selective pressures in the actuation of Swedish gender-neutral "hen"', workshop: ''},
    {id: 359, type: 'poster', day: 'monday', time: '1515', room: '', author: ['Songjun He'], title:'The encliticisation of numeral yi "one" in Mandarin', workshop: ''},
    {id: 202, type: 'poster', day: 'monday', time: '1515', room: '', author: ['Henri Kauhanen'], title:'Dynamical systems - a standard theory for language change?', workshop: ''},
    {id: 219, type: 'poster', day: 'monday', time: '1515', room: '', author: ['Iván Igartua'], title:'Exploring the diachrony of animacy distinctions', workshop: ''},
    {id: 251, type: 'poster', day: 'monday', time: '1515', room: '', author: ['Darya Kavitskaya', 'Adam McCollum'], title:'The development of vowel harmony in Turkic: Phonologization and analogy', workshop: ''},
    {id: 274, type: 'poster', day: 'monday', time: '1515', room: '', author: ['James Baker'], title:'Germanic as a parametric anomaly within Indo-European', workshop: ''},
    {id: 288, type: 'poster', day: 'monday', time: '1515', room: '', author: ['Michael Frotscher'], title:' Cliticisation processes and the emergence of complex derivational morphology - decomposition and non-linear concatenation', workshop: ''},
    {id: 318, type: 'poster', day: 'monday', time: '1515', room: '', author: ['Veronika Hegedus','Katalin Gugán'], title:'Word order change and the position of verb modifiers in Hungarian', workshop: ''},
    {id: 363, type: 'poster', day: 'monday', time: '1515', room: '', author: ['Christian Rapold'], title:' Laterals fricatives/affricates and their relevance for the classification of South Cushitic', workshop: ''},

    {id: 193, type: 'poster', day: 'monday', time: '1515', room: '', author: ['Will Thurlwell'], title:'Instrumentality and the Instrumental Case in Old High German and Old Saxon', workshop: ''},
    {id: 324, type: 'poster', day: 'monday', time: '1515', room: '', author: ['Hanne Eckhoff and Nilo Pedrazzini'], title:' Parallel data for semantic analyses of ancient languages: Greek conjunct participles', workshop: ''},
    {id: 329, type: 'poster', day: 'monday', time: '1515', room: '', author: ['Shatha Alruwaili', 'Mohammad Al-Khresheh'], title:' Lexical innovations in English in response to the Covid crisis', workshop: ''},
    {id: 343, type: 'poster', day: 'monday', time: '1515', room: '', author: ['Sampsa Holopainen'], title:' On the development of vowels in the Ugric languages and the problem of Proto-Ugric', workshop: ''},
    {id: 334, type: 'poster', day: 'monday', time: '1515', room: '', author: ['Felicia Stich'], title:'Socio-cognitive factors in the pejoration of German words for women ', workshop: ''},

    {id: 0, type: 'poster', day: 'monday', time: '1515', room: '', author: [''], title:'', workshop: ''},

    // {id: 0, type: 'talk', day: 'monday', time: '1445', room: 'L6', author: [''], title:'', workshop: ''},
]

/* Code for Sanity Check 
let ids = data.map(datum => datum.id)
let titles = data.map(datum => datum.title)
let idsSet = new Set(ids)
let titleSet = new Set(titles)
if (ids.length == idsSet.length){console.log("all ids unique")}else{console.log("duplicate ids found")}
if (titles.length == titleSet.length){console.log("all titles unique")}else{console.log("duplicate titles found")}
*/